better error reporting, incl. testing

diff --git a/bin/zedo b/bin/zedo
--- a/bin/zedo
+++ b/bin/zedo
@@ -137,10 +137,14 @@ if [ -z "$ZEDO__TARGET" ]; then
   export ZEDO__ROOT_ERR
   # NOTE zedo should only use $ZEDO__ROOT_ERR to log to top, only do-scripts can use fd 3
 
-  ZEDO__CALLSTACK="$ZEDO__ROOT/.zedo/log/callstack.zedolog"
-  mkdir -p "$(dirname "$ZEDO__CALLSTACK")"
+  __logDir="$ZEDO__ROOT/.zedo/log"
+  mkdir -p "$__logDir"
+  ZEDO__CALLSTACK="$__logDir/callstack.zedolog"
+  ZEDO__STACKTRACE="$__logDir/stacktrace.zedolog"
   truncate -s0 "$ZEDO__CALLSTACK"
+  [ -e "$ZEDO__STACKTRACE" ] && rm -f "$ZEDO__STACKTRACE"
   export ZEDO__CALLSTACK
+  export ZEDO__STACKTRACE
 
   rm -rf "$ZEDO__ROOT/.zedo/.done"
   rm -rf "$ZEDO__ROOT/.zedo/.when-done"
@@ -353,10 +357,15 @@ __zedoBuild() {
       fi
       cd "$owd"
       if [ $ec != 0 ]; then
-        echo "do-script failed: '$scriptFile $arg1/$arg2$arg3'" | tee "$ZEDO__ROOT_ERR" >&2
-        echo >"$ZEDO__ROOT_ERR" "=================="
-        cat >"$ZEDO__ROOT_ERR" "$logFile"
-        echo >"$ZEDO__ROOT_ERR" "=================="
+        echo >&2 "do-script failed: '$scriptFile $arg1/$arg2$arg3'"
+        echo >>"$ZEDO__STACKTRACE" "$logFile"
+        if [ -z "$ZEDO__PARENT" ]; then
+          local frameLogFile
+          while IFS= read -r frameLogFile; do
+            echo >"$ZEDO__ROOT_ERR" "[START LOGFILE] $(basename "$frameLogFile")"
+            cat >"$ZEDO__ROOT_ERR" "$frameLogFile"
+          done < <(tac "$ZEDO__STACKTRACE")
+        fi
         exit $ec
       else
         mkdir -p "$(dirname "$ZEDO__ROOT/.zedo/.done/$targetPath")"
